# SmokeyEmber for Kitty
# Orange marks interaction; grey-lavender defines structure.

foreground #C8C7D0
background #0B0B0F
selection_foreground #ECEAF1
selection_background #332F3D

cursor #FF6B35
cursor_text_color #0B0B0F
url_color #9D7CD8

active_border_color #A79ABD
inactive_border_color #332F3D
bell_border_color #FF6B35

tab_bar_background #07070A
active_tab_foreground #0B0B0F
active_tab_background #FF6B35
inactive_tab_foreground #8176A5
inactive_tab_background #121218

color0 #0B0B0F
color1 #D9572B
color2 #7FA477
color3 #E89A5B
color4 #7F8FBE
color5 #9D7CD8
color6 #77A6A1
color7 #C8C7D0
color8 #8176A5
color9 #FF7A50
color10 #99B891
color11 #FFB16E
color12 #9DACD2
color13 #B89EE7
color14 #93C1BC
color15 #ECEAF1
